Fix syntax errors in file existence check

diff --git a/.github/workflows/job6.yml b/.github/workflows/job6.yml
--- a/.github/workflows/job6.yml
+++ b/.github/workflows/job6.yml
@@ -5,11 +5,12 @@ jobs:
    runs-on: ubuntu-latest
    steps:
      - name : check if file exsits
+      
        run: |
-         if[ -f config.yml]; then
-           echo ""::debug::config.yml exsits""
-         else
-           echo ""::error::config.yml not exsit""
-           exit 1
-         fi
-         
+          if [ -f config.yml ]; then
+            echo "::debug::config.yml exists"
+          else
+            echo "::error::config.yml does not exist"
+            exit 1
+          fi
+
